[versions]
kotlin = "2.4.10"
spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
jib = "3.5.4"
ktlint = "14.2.0"
jackson3 = "3.2.2"
jackson-annotations = "2.22"
jackson2-bom = "2.22.2"
aws-sdk = "2.54.12"
mockk = "1.14.11"

[libraries]
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson-annotations" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson3" }
jackson-kotlin = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson3" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
aws-sdk-bom = { module = "software.amazon.awssdk:bom", version.ref = "aws-sdk" }
aws-sdk-s3 = { module = "software.amazon.awssdk:s3" }
aws-sdk-url-connection-client = { module = "software.amazon.awssdk:url-connection-client" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient" }
spring-boot-starter-kafka = { module = "org.springframework.boot:spring-boot-starter-kafka" }
spring-kafka-test = { module = "org.springframework.kafka:spring-kafka-test" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
