server:
  port: 8081

spring:
  application:
    name: inventory-state
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/inventory-state}
    representation:
      uuid: standard

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
